### ISSUE TITLE
Refactor repo for consistency

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-mono#21]
Fix below changes as part of playground-mono repo:
- [ ] Use the word `DiceDB` and not `Dice`, every where, there are variable and config places where the word `Dice` is used.
- [ ] Rename config “REQUEST_LIMIT” should be “REQUEST_LIMIT_PER_MIN”
- [ ] Rename config “REQUEST_WINDOW” should be “REQUEST_WINDOW_SEC”
- [ ] Remove package internals/cmds, we can move that struct to `httpServer.go`
- [ ] Rename the endpoint as `/cli`, let’s call it `/shell/exec`. (Remember to add Frontend changes for the same)
- [ ] All errors to be standardized w.r.t casing. We shall change everything to be lowercase.
- [ ] Change filename: `server/httpServer.go -> server/http.go`
- [ ] Update “errorResponse” function to JSON marshal and not string format.
- [ ] Currently log and slog are both being used, let’s just use slog everywhere.
- [ ] Rename pkg/util/helpers.go -> `util/httpHelper.go`

**Comment by rishavvajpayee** [comment]
Hey @lucifercr07 i can take this up

**Comment by lucifercr07** [comment]
@rishavvajpayee assigned, thanks for contributing.

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/playground-mono/pull/24
