### ISSUE TITLE
Use go-dice SDK's `Do` method for calling DiceDB commands. 

### ISSUE THREAD

**Issue by KaviiSuri** [DiceDB/playground-mono#25]
The go-dice SDK is a fork of go-redis, thus also have `Do` method. This method allows for any arbitrary command and argument list to be sent to the db without any validation on the sdk. 

This is more inline with our requirements on playground, since we just allow everything (except black listed commands) to be executed. The current approach of parsing the content, only to be re-encoded as RESP and re-parsed later at db level is bug-prone, hard to modify/maintain and adds additional work to get it working.

`Do` method - https://github.com/DiceDB/go-dice/blob/d97f15fca831183200ba9b9b19a6ab798a0f6c21/README.md?plain=1#L226

https://pkg.go.dev/github.com/redis/go-redis/v9#Client.Do

## Approach
1. should use `Do` method to forward the commands to dicedb, without parsing them manually. 
2. should ensure black listed commands are not possible to executed
3. error handling should be done properly, similar to how it's done on the CLI
4. clean up the code related to parsing and calling specific commands on the dicedb client (switch cases on "GET", "SET" etc)

**Comment by rishavvajpayee** [comment]
hey i can take this up @KaviiSuri

**Comment by pawansoni007** [comment]
@KaviiSuri  can I take this up? Please!

**Comment by lucifercr07** [comment]
Closing, merged as part of https://github.com/DiceDB/playground-mono/pull/26
