### ISSUE TITLE
Add integration tests for commands execution (1)

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-mono#28]
This issue involves creating the test cases for `playground-mono` repo:

**Source**: `internal/tests/integration/commands/`

- `set_test.go`
- `get_test.go`
- `incr_test.go`
- `echo_test.go`

Steps:

1. Create the corresponding tests for these commands in `internal/tests/integration/commands/`
2. We can use [this](https://github.com/DiceDB/dice/blob/master/integration_tests/commands/http/set_test.go) file from `dice` repo for reference.
3. Run the tests and fix issues with command parsing in HTTP.

If you need to do anything **custom** feel free to comment on this issue for more details.

**NOTE**: Please consider that for the integration tests we should ideally have a dice server spin up via Docker container in Go and then write integration tests. We can use Go Libraries like testcontainers-go for this.

**Comment by Dhroov7** [comment]
@lucifercr07 Can you please assign me this issue?

**Comment by lucifercr07** [comment]
@Dhroov7 assigned, thanks for contributing.

**Comment by lucifercr07** [comment]
@Dhroov7 initial structure for integration tests are in, please let us know if any other details are required.

**Comment by Dhroov7** [comment]
@lucifercr07 No, i will pick this up and complete it by End of this week. Let me know if you want it sooner

**Comment by Dhroov7** [comment]
@lucifercr07 Added more tests, Please review
