### ISSUE TITLE
Add integration tests for commands execution (2)

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-mono#29]
This issue involves creating the test cases for `playground-mono` repo:

**Source**: `internal/tests/integration/commands/`

- `exists_test.go`
- `expire_test.go`
- `expireat_test.go`
- `expiretime_test.go`

Steps:

1. Create the corresponding tests for these commands in `internal/tests/integration/commands/`
2. We can use [this](https://github.com/DiceDB/dice/blob/master/integration_tests/commands/http/set_test.go) file from `dice` repo for reference.
3. Run the tests and fix issues with command parsing in HTTP.

If you need to do anything **custom** feel free to comment on this issue for more details.

**NOTE**: Please consider that for the integration tests we should ideally have a dice server spin up via Docker container in Go and then write integration tests. We can use Go Libraries like testcontainers-go for this.

**Comment by RishabhC-137** [comment]
I will take it @lucifercr07

**Comment by lucifercr07** [comment]
@RishabhC-137 initial structure for integration tests are in, please let us know if any other details are required.

**Comment by lucifercr07** [comment]
Closing merged as part of #39
