### ISSUE TITLE
Add integration tests for commands execution for hashes datastructure

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-mono#31]
This issue involves creating the test cases for `playground-mono` repo:

**Source**: `internal/tests/integration/commands/`

- `hset_test.go`
- `hget_test.go`
- `hgetall_test.go`
- `hincrby_test.go`
- `hmget_test.go`

Steps:

1. Create the corresponding tests for these commands in `internal/tests/integration/commands/`
2. We can use [this](https://github.com/DiceDB/dice/blob/master/integration_tests/commands/http/set_test.go) file from `dice` repo for reference.
3. Run the tests and fix issues with command parsing in server.

If you need to do anything **custom** feel free to comment on this issue for more details.

**NOTE**: Please consider that for the integration tests we should ideally have a dice server spin up via Docker container in Go and then write integration tests. We can use Go Libraries like testcontainers-go for this.

**Comment by anishkoulgi** [comment]
Hi @lucifercr07, I can pick this up, please assign this issue to me.

**Comment by lucifercr07** [comment]
@anishkoulgi assigned, thanks for contributing.
