### ISSUE TITLE
Update headers to send `x-next-cleanup-time` instead of `x-last-cleanup-time`

### ISSUE THREAD

**Issue by lucifercr07** [DiceDB/playground-mono#47]
- Update headers to send `x-next-cleanup-time` instead of `x-last-cleanup-time` so that FE doesn't need to handle the logic to get next cleanup time.
- Update existing `/health` API to return headers. This would help FE to populate values at load.
- Add unit tests/integration tests for the same.

**Comment by Dev79844** [comment]
Hey @lucifercr07 
Can you assign it to me?

**Comment by aasifkhan7** [comment]
@lucifercr07

**Comment by lucifercr07** [comment]
Closing merged as part of https://github.com/DiceDB/playground-mono/pull/48
